<template>
  <div class="bg-gray-100 dark:bg-zinc-800 m-6 p-6 shadow-md hover:shadow-none hover:rounded motion-safe:animate-fade-in">
    <form  @submit.prevent="openMail">
      <div class="flex flex-wrap md:flex-nowrap">
        <div :class="`w-full ${isError ? 'md:w-1/2' : 'md:w-2/3'} p-6 mx-auto`">
          <label for="name">Name</label>
          <br />
          <input
            v-model="name"
            name="name"
            required
            class="w-full px-4 py-2 bg-gray-200 dark:bg-zinc-700 rounded-lg"
          />

          <br />

          <label for="topic">Topic</label>
          <br />
          <input
            v-model="topic"
            name="topic"
            required
            :placeholder="isError ? `${$route.query.statusCode} error` : ''"
            class="w-full px-4 py-2 bg-gray-200 dark:bg-zinc-700 rounded-lg"
          />

          <div v-if="!isError">
            <label for="message">Message</label>
            <br />
            <textarea
              v-model="message"
              name="message"
              required
              placeholder="Your website is awesome! 🤩"
              class="w-full h-32 resize-none px-4 py-2 bg-gray-200 dark:bg-zinc-700 rounded-lg"
            />
          </div>

          <div v-if="isError">
            <label for="extraFeedback">Describe what happened when this error occurred</label>
            <br />
            <textarea
              v-model="extraFeedback"
              name="extraFeedback"
              placeholder="I saw an error when I tried viewing the blog post about your multiplayer pac-man game, CyRun."
              class="w-full h-32 resize-none px-4 py-2 bg-gray-200 dark:bg-zinc-700 rounded-lg"
            />
          </div>
        </div>

        <div v-if="isError" class="w-full md:w-1/2 mx-auto p-6 mx-auto">
          <p class="text-lg font-bold">Error information 🤓</p>
          <p class="text-xs text-gray-600 dark:text-gray-300">This information was generated by the error you received.</p>
          <div v-if="$route.query.statusCode">
            <label for="statusCode">Status Code</label>
            <br />
            <input
              name="statusCode"
              :value="$route.query.statusCode"
              disabled
              class="w-full px-4 py-2 bg-gray-100 bg-gray-200 dark:bg-zinc-700 border-gray-300 border-2 rounded-lg"
            />
          </div>

          <div v-if="$route.query.path">
            <label for="path">Path</label>
            <br />
            <input
              name="path"
              :value="$route.query.path"
              disabled
              class="w-full px-4 py-2 bg-gray-100 bg-gray-200 dark:bg-zinc-700 border-gray-300 border-2 rounded-lg"
            />
          </div>

          <div v-if="$route.query.detail">
            <label for="errorDetails">Error detail</label>
            <br />
            <textarea
              name="errorDetails"
              :value="$route.query.detail"
              disabled
              class="w-full h-32 resize-none px-4 py-2 bg-gray-200 dark:bg-zinc-700 border-gray-300 border-2 rounded-lg"
            />
          </div>
        </div>
      </div>

      <div :class="`${!isError ? 'md:w-2/3' : ''} mx-auto p-6`">
        <input
          type="submit"
          value="Continue"
          :class="`border-2 rounded-md p-1 bg-gray-600 text-white transition-opacity duration-1000 ${name || topic || message || extraFeedback ? 'opacity-1' : 'opacity-25'}`"
        />
        <p :class="`text-xs text-gray-600 dark:text-gray-300 transition-opacity duration-1000 ${name || topic || message || extraFeedback ? 'opacity-1' : 'opacity-0'}`">
          An email will be generated for you based on the information you provided above. All you have to do is press send.
        </p>
      </div>
    </form>
  </div>
</template>

<script>
export default {
  name: 'contact-form',
  data: () => ({
    name: undefined,
    topic: undefined,
    message: undefined,
    extraFeedback: undefined,
  }),
  computed: {
    isError() {
      return Object.keys(this.$route?.query).length && this.$route?.query.statusCode;
    },
    mailLink() {
      const statusCode = `Status Code: ${this.$route?.query.statusCode || '---' }`;
      const path = `Status Code: ${this.$route?.query.path || '---' }`;
      const detail = `Status Code: ${this.$route?.query.detail || '---' }`;
      let body;

      if (this.isError) {
        body = `Error information:\n${statusCode}\n${path}\n${detail}\n\nFeedback:\n${this.extraFeedback || 'Not provided'}\n\nFeedback provided by: ${this.name || 'anonymous'}`;
      }
      else {
        body = `${this.message}\n\nFrom: ${this.name || 'anonymous'}`;
      }
      
      return `mailto:lisleachristian@gmail.com?subject=${encodeURIComponent(this.topic || 'Website Contact Form')}&body=${encodeURIComponent(body)}`;
    }
  },
  methods: {
    openMail() {
      location.href = this.mailLink;
    }
  }
};
</script>