import Chance from "chance";

const chance = new Chance();

describe('Contact page', () => {
  before(() => {
    if (!Cypress.env('NUXT_ENV_EMAIL_ADDRESS')) {
      throw new Error('Required Environment Variable NUXT_ENV_EMAIL_ADDRESS is incorrectly set');
    }
  });

  beforeEach(() => {
    cy.visit('/contact');
    cy.wait(500);
  });

  it('shows the menu and footer bar', () => {
    cy.get('#nav-bar').should('be.visible');
    cy.get('#footer-bar').scrollIntoView({duration: 500 });
    cy.get('#footer-bar').should('be.visible');
  });

  it('shows the "contact" header and form cards', () => {
    cy.get("#contact-header-card").should('be.visible');
    cy.get('#contact-form-card').should('be.visible');
  });

  describe('when a user submits the form', () => {
    let fakeResponse;

    beforeEach(() => {
      fakeResponse = {
        name: chance.name(),
        topic: chance.sentence(),
        message: chance.paragraph()
      };

      cy.get('form').scrollIntoView();
      cy.get('[name="name"]').type(fakeResponse.name);
      cy.get('[name="topic"]').type(fakeResponse.topic);
      cy.get('[name="message"]').type(fakeResponse.message);
      cy.wait(500);
      cy.get('[type="submit"]').click();
    });

    it('shows the "Thanks for reaching out!" message', () => {
      cy.contains('Thanks for reaching out!');
    });

    it('shows the mailto link that was generated by the form submission', () => {
      cy.contains('Click here to open the email link')
        .find('a')
        .should('have.attr', 'href')
        .and('include', `mailto:`);
    });
  });
});
